/**
 * Dynamic Client Registration (RFC 7591)
 *
 * Allows OAuth 2.0 clients to register with the authorization server
 * without requiring manual pre-registration
 */

import crypto from 'crypto';

/**
 * Client types
 */
export enum ClientType {
  CONFIDENTIAL = 'confidential', // Can securely store credentials
  PUBLIC = 'public', // Cannot securely store credentials (SPAs, mobile apps)
}

/**
 * Token endpoint authentication methods
 */
export enum TokenEndpointAuthMethod {
  CLIENT_SECRET_BASIC = 'client_secret_basic',
  CLIENT_SECRET_POST = 'client_secret_post',
  CLIENT_SECRET_JWT = 'client_secret_jwt',
  PRIVATE_KEY_JWT = 'private_key_jwt',
  NONE = 'none', // For public clients
}

/**
 * Client metadata for registration
 */
export interface ClientMetadata {
  // Client identifiers
  client_id?: string; // Generated by server
  client_secret?: string; // Generated for confidential clients
  client_id_issued_at?: number; // Unix timestamp
  client_secret_expires_at?: number; // Unix timestamp (0 = never expires)

  // Client information
  client_name?: string;
  client_uri?: string;
  logo_uri?: string;
  contacts?: string[]; // Email addresses

  // OAuth parameters
  redirect_uris: string[]; // REQUIRED
  token_endpoint_auth_method?: TokenEndpointAuthMethod;
  grant_types?: string[];
  response_types?: string[];
  scope?: string;

  // Client type
  client_type?: ClientType;

  // Advanced parameters
  jwks_uri?: string; // URL for client's JWK Set
  jwks?: any; // Client's JWK Set (alternative to jwks_uri)
  software_id?: string; // Identifier for client software
  software_version?: string; // Version of client software

  // RFC 8707: Resource indicators
  resource?: string[]; // Resources this client can access

  // MCP specific
  mcp_version?: string;
  mcp_capabilities?: string[];
}

/**
 * Client registration request
 */
export interface ClientRegistrationRequest {
  redirect_uris: string[];
  token_endpoint_auth_method?: TokenEndpointAuthMethod;
  grant_types?: string[];
  response_types?: string[];
  client_name?: string;
  client_uri?: string;
  logo_uri?: string;
  scope?: string;
  contacts?: string[];
  jwks_uri?: string;
  jwks?: any;
  software_id?: string;
  software_version?: string;
  resource?: string[];
}

/**
 * Client registration response
 */
export interface ClientRegistrationResponse extends ClientMetadata {
  client_id: string;
  client_secret?: string;
  client_id_issued_at: number;
  client_secret_expires_at: number;
  registration_access_token?: string;
  registration_client_uri?: string;
}

/**
 * Registered client
 */
export interface RegisteredClient {
  clientId: string;
  clientSecret?: string;
  metadata: ClientMetadata;
  createdAt: Date;
  lastUsedAt?: Date;
}

/**
 * Client store interface
 */
export interface ClientStore {
  create(client: RegisteredClient): Promise<void>;
  get(clientId: string): Promise<RegisteredClient | null>;
  update(clientId: string, metadata: Partial<ClientMetadata>): Promise<void>;
  delete(clientId: string): Promise<void>;
  findBySecret(clientSecret: string): Promise<RegisteredClient | null>;
}

/**
 * In-memory client store (for development)
 */
export class InMemoryClientStore implements ClientStore {
  private clients = new Map<string, RegisteredClient>();

  async create(client: RegisteredClient): Promise<void> {
    this.clients.set(client.clientId, client);
  }

  async get(clientId: string): Promise<RegisteredClient | null> {
    return this.clients.get(clientId) || null;
  }

  async update(clientId: string, metadata: Partial<ClientMetadata>): Promise<void> {
    const client = this.clients.get(clientId);
    if (client) {
      client.metadata = { ...client.metadata, ...metadata };
    }
  }

  async delete(clientId: string): Promise<void> {
    this.clients.delete(clientId);
  }

  async findBySecret(clientSecret: string): Promise<RegisteredClient | null> {
    for (const client of this.clients.values()) {
      if (client.clientSecret === clientSecret) {
        return client;
      }
    }
    return null;
  }

  clear(): void {
    this.clients.clear();
  }

  size(): number {
    return this.clients.size;
  }
}

/**
 * Client Registration Service
 */
export class ClientRegistrationService {
  constructor(private clientStore: ClientStore) {}

  /**
   * Register a new client
   */
  async registerClient(request: ClientRegistrationRequest): Promise<ClientRegistrationResponse> {
    // Validate request
    this.validateRegistrationRequest(request);

    // Generate client credentials
    const clientId = this.generateClientId();
    const clientType = this.determineClientType(request);
    const clientSecret = clientType === ClientType.CONFIDENTIAL
      ? this.generateClientSecret()
      : undefined;

    const now = Math.floor(Date.now() / 1000);

    // Build client metadata
    const metadata: ClientMetadata = {
      client_id: clientId,
      client_secret: clientSecret,
      client_id_issued_at: now,
      client_secret_expires_at: 0, // Never expires
      redirect_uris: request.redirect_uris,
      token_endpoint_auth_method: request.token_endpoint_auth_method ||
        (clientSecret ? TokenEndpointAuthMethod.CLIENT_SECRET_BASIC : TokenEndpointAuthMethod.NONE),
      grant_types: request.grant_types || ['authorization_code'],
      response_types: request.response_types || ['code'],
      client_name: request.client_name,
      client_uri: request.client_uri,
      logo_uri: request.logo_uri,
      scope: request.scope,
      contacts: request.contacts,
      client_type: clientType,
      jwks_uri: request.jwks_uri,
      jwks: request.jwks,
      software_id: request.software_id,
      software_version: request.software_version,
      resource: request.resource,
      mcp_version: '2025-06-18',
    };

    // Store client
    await this.clientStore.create({
      clientId,
      clientSecret,
      metadata,
      createdAt: new Date(),
    });

    // Return registration response
    return {
      ...metadata,
      client_id: clientId,
      client_secret: clientSecret,
      client_id_issued_at: now,
      client_secret_expires_at: 0,
    };
  }

  /**
   * Get client by ID
   */
  async getClient(clientId: string): Promise<RegisteredClient | null> {
    return this.clientStore.get(clientId);
  }

  /**
   * Validate client credentials
   */
  async validateCredentials(clientId: string, clientSecret?: string): Promise<boolean> {
    const client = await this.clientStore.get(clientId);

    if (!client) {
      return false;
    }

    // Public clients don't have secrets
    if (client.metadata.client_type === ClientType.PUBLIC) {
      return clientSecret === undefined;
    }

    // Confidential clients must provide matching secret
    return client.clientSecret === clientSecret;
  }

  /**
   * Validate redirect URI
   */
  async validateRedirectUri(clientId: string, redirectUri: string): Promise<boolean> {
    const client = await this.clientStore.get(clientId);

    if (!client) {
      return false;
    }

    return client.metadata.redirect_uris.includes(redirectUri);
  }

  /**
   * Update client
   */
  async updateClient(clientId: string, updates: Partial<ClientMetadata>): Promise<void> {
    await this.clientStore.update(clientId, updates);
  }

  /**
   * Delete client
   */
  async deleteClient(clientId: string): Promise<void> {
    await this.clientStore.delete(clientId);
  }

  /**
   * Validate registration request
   */
  private validateRegistrationRequest(request: ClientRegistrationRequest): void {
    // Redirect URIs are required
    if (!request.redirect_uris || request.redirect_uris.length === 0) {
      throw new Error('redirect_uris is required');
    }

    // Validate redirect URI format
    for (const uri of request.redirect_uris) {
      try {
        const url = new URL(uri);

        // Must use HTTPS in production (except localhost)
        if (url.protocol !== 'https:' && url.hostname !== 'localhost' && url.hostname !== '127.0.0.1') {
          throw new Error(`Redirect URI must use HTTPS: ${uri}`);
        }
      } catch (error) {
        throw new Error(`Invalid redirect URI: ${uri}`);
      }
    }

    // Validate grant types
    const validGrantTypes = [
      'authorization_code',
      'client_credentials',
      'refresh_token',
      'urn:ietf:params:oauth:grant-type:token-exchange', // RFC 8693 Token Exchange
    ];
    if (request.grant_types) {
      for (const grantType of request.grant_types) {
        if (!validGrantTypes.includes(grantType)) {
          throw new Error(`Invalid grant type: ${grantType}`);
        }
      }
    }

    // Validate response types
    const validResponseTypes = ['code', 'token', 'code token'];
    if (request.response_types) {
      for (const responseType of request.response_types) {
        if (!validResponseTypes.includes(responseType)) {
          throw new Error(`Invalid response type: ${responseType}`);
        }
      }
    }
  }

  /**
   * Determine client type from request
   */
  private determineClientType(request: ClientRegistrationRequest): ClientType {
    // If token_endpoint_auth_method is 'none', it's a public client
    if (request.token_endpoint_auth_method === TokenEndpointAuthMethod.NONE) {
      return ClientType.PUBLIC;
    }

    // Default to confidential
    return ClientType.CONFIDENTIAL;
  }

  /**
   * Generate client ID
   */
  private generateClientId(): string {
    return `client_${crypto.randomBytes(16).toString('hex')}`;
  }

  /**
   * Generate client secret
   */
  private generateClientSecret(): string {
    return crypto.randomBytes(32).toString('base64url');
  }
}
